#!/bin/sh
#
# Makefile for FF v 1.0
#


####### FLAGS

TYPE	= 
ADDONS	= 

CC      = gcc

CFLAGS	= -O6 -Wall -g -ansi $(TYPE) $(ADDONS) 
# -g -pg

LIBS    = -lm


####### Files

PDDL_PARSER_SRC	= scan-fct_pddl.tab.c \
	scan-ops_pddl.tab.c \
	scan-probname.tab.c \
	lex.fct_pddl.c \
	lex.ops_pddl.c 

PDDL_PARSER_OBJ = scan-fct_pddl.tab.o \
	scan-ops_pddl.tab.o 


SOURCES 	= main.c \
	memory.c \
	output.c \
	parse.c \
	expressions.c \
	inst_pre.c \
	inst_easy.c \
	inst_hard.c \
	inst_final.c \
	relax.c \
	search.c \
	utility.c

LIB_SOURCES = libff.c \
	memory.c \
	output.c \
	parse.c \
	expressions.c \
	inst_pre.c \
	inst_easy.c \
	inst_hard.c \
	inst_final.c \
	relax.c \
	search.c \
	utility.c


OBJECTS 	= $(SOURCES:.c=.o)
LIB_OBJECTS	= $(LIB_SOURCES:.c=.o)

####### Implicit rules

.SUFFIXES:

.SUFFIXES: .c .o

.c.o:; $(CC) -c $(CFLAGS) $<

####### Build rules

libff: $(LIB_OBJECTS) $(PDDL_PARSER_OBJ)
	ar cru libff.a $(LIB_OBJECTS) $(PDDL_PARSER_OBJ)

ff: $(OBJECTS) $(PDDL_PARSER_OBJ)
	$(CC) -static -o ff $(OBJECTS) $(PDDL_PARSER_OBJ) $(CFLAGS) $(LIBS)

# pddl syntax
scan-fct_pddl.tab.c: scan-fct_pddl.y lex.fct_pddl.c
	bison -pfct_pddl -bscan-fct_pddl scan-fct_pddl.y

scan-ops_pddl.tab.c: scan-ops_pddl.y lex.ops_pddl.c
	bison -pops_pddl -bscan-ops_pddl scan-ops_pddl.y

lex.fct_pddl.c: lex-fct_pddl.l
	flex -Pfct_pddl lex-fct_pddl.l

lex.ops_pddl.c: lex-ops_pddl.l
	flex -Pops_pddl lex-ops_pddl.l

test_lib: test_main.cxx
	g++ -static -o test_lib test_main.cxx -lff -L./

# misc
clean:
	rm -f *.o *.bak *~ *% core *_pure_p9_c0_400.o.warnings test_lib \
        \#*\# $(RES_PARSER_SRC) $(PDDL_PARSER_SRC)

veryclean: clean
	rm -f ff H* J* K* L* O* graph.* *.symbex gmon.out \
	$(PDDL_PARSER_SRC) \
	lex.fct_pddl.c lex.ops_pddl.c lex.probname.c \
	*.output

depend:
	makedepend -- $(SOURCES)  $(LIB_SOURCES) $(PDDL_PARSER_SRC) test_main.cxx

lint:
	lclint -booltype Bool $(SOURCES) 2> output.lint

# DO NOT DELETE

main.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
main.o: /usr/include/_ansi.h /usr/include/newlib.h
main.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
main.o: /usr/include/sys/features.h /usr/include/sys/reent.h
main.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
main.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
main.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
main.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
main.o: /usr/include/strings.h /usr/include/sys/_locale.h
main.o: /usr/include/ctype.h /usr/include/sys/types.h
main.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
main.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
main.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
main.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
main.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
main.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
main.o: /usr/include/endian.h /usr/include/bits/byteswap.h
main.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
main.o: /usr/include/sys/timeb.h /usr/include/sys/times.h memory.h
main.o: /usr/include/string.h /usr/include/sys/string.h output.h parse.h
main.o: expressions.h inst_pre.h inst_easy.h inst_hard.h inst_final.h relax.h
main.o: search.h
memory.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
memory.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
memory.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
memory.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
memory.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
memory.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
memory.o: /usr/include/sys/_locale.h /usr/include/strings.h
memory.o: /usr/include/sys/string.h ff.h /usr/include/stdlib.h
memory.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
memory.o: /usr/include/stdio.h /usr/include/sys/stdio.h /usr/include/ctype.h
memory.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
memory.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
memory.o: /usr/include/bits/endian.h /usr/include/sys/select.h
memory.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
memory.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
memory.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
memory.o: /usr/include/machine/types.h /usr/include/endian.h
memory.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
memory.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
memory.o: /usr/include/sys/times.h memory.h inst_pre.h
output.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
output.o: /usr/include/_ansi.h /usr/include/newlib.h
output.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
output.o: /usr/include/sys/features.h /usr/include/sys/reent.h
output.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
output.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
output.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
output.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
output.o: /usr/include/strings.h /usr/include/sys/_locale.h
output.o: /usr/include/ctype.h /usr/include/sys/types.h
output.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
output.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
output.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
output.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
output.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
output.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
output.o: /usr/include/endian.h /usr/include/bits/byteswap.h
output.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
output.o: /usr/include/sys/timeb.h /usr/include/sys/times.h utility.h
output.o: output.h
parse.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
parse.o: /usr/include/_ansi.h /usr/include/newlib.h
parse.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
parse.o: /usr/include/sys/features.h /usr/include/sys/reent.h
parse.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
parse.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
parse.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
parse.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
parse.o: /usr/include/strings.h /usr/include/sys/_locale.h
parse.o: /usr/include/ctype.h /usr/include/sys/types.h
parse.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
parse.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
parse.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
parse.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
parse.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
parse.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
parse.o: /usr/include/endian.h /usr/include/bits/byteswap.h
parse.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
parse.o: /usr/include/sys/timeb.h /usr/include/sys/times.h memory.h
parse.o: /usr/include/string.h /usr/include/sys/string.h output.h parse.h
expressions.o: /usr/include/string.h /usr/include/_ansi.h
expressions.o: /usr/include/newlib.h /usr/include/_newlib_version.h
expressions.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
expressions.o: /usr/include/sys/features.h /usr/include/sys/reent.h
expressions.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
expressions.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
expressions.o: /usr/include/sys/lock.h /usr/include/sys/_locale.h
expressions.o: /usr/include/strings.h /usr/include/sys/string.h ff.h
expressions.o: /usr/include/stdlib.h /usr/include/machine/stdlib.h
expressions.o: /usr/include/alloca.h /usr/include/stdio.h
expressions.o: /usr/include/sys/stdio.h /usr/include/ctype.h
expressions.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
expressions.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
expressions.o: /usr/include/bits/endian.h /usr/include/sys/select.h
expressions.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
expressions.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
expressions.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
expressions.o: /usr/include/machine/types.h /usr/include/endian.h
expressions.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
expressions.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
expressions.o: /usr/include/sys/times.h output.h memory.h expressions.h
inst_pre.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
inst_pre.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_pre.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
inst_pre.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
inst_pre.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
inst_pre.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
inst_pre.o: /usr/include/sys/_locale.h /usr/include/strings.h
inst_pre.o: /usr/include/sys/string.h ff.h /usr/include/stdlib.h
inst_pre.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
inst_pre.o: /usr/include/stdio.h /usr/include/sys/stdio.h
inst_pre.o: /usr/include/ctype.h /usr/include/sys/types.h
inst_pre.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
inst_pre.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
inst_pre.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
inst_pre.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
inst_pre.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
inst_pre.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
inst_pre.o: /usr/include/endian.h /usr/include/bits/byteswap.h
inst_pre.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
inst_pre.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h
inst_pre.o: memory.h expressions.h inst_pre.h
inst_easy.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_easy.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_easy.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_easy.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_easy.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_easy.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_easy.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_easy.o: /usr/include/alloca.h /usr/include/stdio.h
inst_easy.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_easy.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_easy.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_easy.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_easy.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_easy.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_easy.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_easy.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_easy.o: /usr/include/machine/types.h /usr/include/endian.h
inst_easy.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_easy.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_easy.o: /usr/include/sys/times.h output.h memory.h /usr/include/string.h
inst_easy.o: /usr/include/sys/string.h expressions.h inst_pre.h inst_easy.h
inst_hard.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_hard.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_hard.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_hard.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_hard.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_hard.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_hard.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_hard.o: /usr/include/alloca.h /usr/include/stdio.h
inst_hard.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_hard.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_hard.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_hard.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_hard.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_hard.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_hard.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_hard.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_hard.o: /usr/include/machine/types.h /usr/include/endian.h
inst_hard.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_hard.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_hard.o: /usr/include/sys/times.h output.h memory.h /usr/include/string.h
inst_hard.o: /usr/include/sys/string.h expressions.h inst_pre.h inst_hard.h
inst_final.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_final.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_final.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_final.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_final.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_final.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_final.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_final.o: /usr/include/alloca.h /usr/include/stdio.h
inst_final.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_final.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_final.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_final.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_final.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_final.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_final.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_final.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_final.o: /usr/include/machine/types.h /usr/include/endian.h
inst_final.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_final.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_final.o: /usr/include/sys/times.h output.h memory.h
inst_final.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
inst_final.o: inst_pre.h inst_final.h
relax.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
relax.o: /usr/include/_ansi.h /usr/include/newlib.h
relax.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
relax.o: /usr/include/sys/features.h /usr/include/sys/reent.h
relax.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
relax.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
relax.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
relax.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
relax.o: /usr/include/strings.h /usr/include/sys/_locale.h
relax.o: /usr/include/ctype.h /usr/include/sys/types.h
relax.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
relax.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
relax.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
relax.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
relax.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
relax.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
relax.o: /usr/include/endian.h /usr/include/bits/byteswap.h
relax.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
relax.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h memory.h
relax.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
relax.o: relax.h search.h
search.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
search.o: /usr/include/_ansi.h /usr/include/newlib.h
search.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
search.o: /usr/include/sys/features.h /usr/include/sys/reent.h
search.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
search.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
search.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
search.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
search.o: /usr/include/strings.h /usr/include/sys/_locale.h
search.o: /usr/include/ctype.h /usr/include/sys/types.h
search.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
search.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
search.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
search.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
search.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
search.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
search.o: /usr/include/endian.h /usr/include/bits/byteswap.h
search.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
search.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h memory.h
search.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
search.o: relax.h search.h
utility.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
utility.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
utility.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
utility.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
utility.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
utility.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
utility.o: /usr/include/sys/_locale.h /usr/include/strings.h
utility.o: /usr/include/sys/string.h utility.h ff.h /usr/include/stdlib.h
utility.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
utility.o: /usr/include/stdio.h /usr/include/sys/stdio.h /usr/include/ctype.h
utility.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
utility.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
utility.o: /usr/include/bits/endian.h /usr/include/sys/select.h
utility.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
utility.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
utility.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
utility.o: /usr/include/machine/types.h /usr/include/endian.h
utility.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
utility.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
utility.o: /usr/include/sys/times.h output.h
libff.o: libff.h ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
libff.o: /usr/include/_ansi.h /usr/include/newlib.h
libff.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
libff.o: /usr/include/sys/features.h /usr/include/sys/reent.h
libff.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
libff.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
libff.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
libff.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
libff.o: /usr/include/strings.h /usr/include/sys/_locale.h
libff.o: /usr/include/ctype.h /usr/include/sys/types.h
libff.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
libff.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
libff.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
libff.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
libff.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
libff.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
libff.o: /usr/include/endian.h /usr/include/bits/byteswap.h
libff.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
libff.o: /usr/include/sys/timeb.h /usr/include/sys/times.h memory.h
libff.o: /usr/include/string.h /usr/include/sys/string.h output.h parse.h
libff.o: expressions.h inst_pre.h inst_easy.h inst_hard.h inst_final.h
memory.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
memory.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
memory.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
memory.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
memory.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
memory.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
memory.o: /usr/include/sys/_locale.h /usr/include/strings.h
memory.o: /usr/include/sys/string.h ff.h /usr/include/stdlib.h
memory.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
memory.o: /usr/include/stdio.h /usr/include/sys/stdio.h /usr/include/ctype.h
memory.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
memory.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
memory.o: /usr/include/bits/endian.h /usr/include/sys/select.h
memory.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
memory.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
memory.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
memory.o: /usr/include/machine/types.h /usr/include/endian.h
memory.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
memory.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
memory.o: /usr/include/sys/times.h memory.h inst_pre.h
output.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
output.o: /usr/include/_ansi.h /usr/include/newlib.h
output.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
output.o: /usr/include/sys/features.h /usr/include/sys/reent.h
output.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
output.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
output.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
output.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
output.o: /usr/include/strings.h /usr/include/sys/_locale.h
output.o: /usr/include/ctype.h /usr/include/sys/types.h
output.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
output.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
output.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
output.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
output.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
output.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
output.o: /usr/include/endian.h /usr/include/bits/byteswap.h
output.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
output.o: /usr/include/sys/timeb.h /usr/include/sys/times.h utility.h
output.o: output.h
parse.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
parse.o: /usr/include/_ansi.h /usr/include/newlib.h
parse.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
parse.o: /usr/include/sys/features.h /usr/include/sys/reent.h
parse.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
parse.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
parse.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
parse.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
parse.o: /usr/include/strings.h /usr/include/sys/_locale.h
parse.o: /usr/include/ctype.h /usr/include/sys/types.h
parse.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
parse.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
parse.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
parse.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
parse.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
parse.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
parse.o: /usr/include/endian.h /usr/include/bits/byteswap.h
parse.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
parse.o: /usr/include/sys/timeb.h /usr/include/sys/times.h memory.h
parse.o: /usr/include/string.h /usr/include/sys/string.h output.h parse.h
expressions.o: /usr/include/string.h /usr/include/_ansi.h
expressions.o: /usr/include/newlib.h /usr/include/_newlib_version.h
expressions.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
expressions.o: /usr/include/sys/features.h /usr/include/sys/reent.h
expressions.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
expressions.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
expressions.o: /usr/include/sys/lock.h /usr/include/sys/_locale.h
expressions.o: /usr/include/strings.h /usr/include/sys/string.h ff.h
expressions.o: /usr/include/stdlib.h /usr/include/machine/stdlib.h
expressions.o: /usr/include/alloca.h /usr/include/stdio.h
expressions.o: /usr/include/sys/stdio.h /usr/include/ctype.h
expressions.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
expressions.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
expressions.o: /usr/include/bits/endian.h /usr/include/sys/select.h
expressions.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
expressions.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
expressions.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
expressions.o: /usr/include/machine/types.h /usr/include/endian.h
expressions.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
expressions.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
expressions.o: /usr/include/sys/times.h output.h memory.h expressions.h
inst_pre.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
inst_pre.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_pre.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
inst_pre.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
inst_pre.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
inst_pre.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
inst_pre.o: /usr/include/sys/_locale.h /usr/include/strings.h
inst_pre.o: /usr/include/sys/string.h ff.h /usr/include/stdlib.h
inst_pre.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
inst_pre.o: /usr/include/stdio.h /usr/include/sys/stdio.h
inst_pre.o: /usr/include/ctype.h /usr/include/sys/types.h
inst_pre.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
inst_pre.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
inst_pre.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
inst_pre.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
inst_pre.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
inst_pre.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
inst_pre.o: /usr/include/endian.h /usr/include/bits/byteswap.h
inst_pre.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
inst_pre.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h
inst_pre.o: memory.h expressions.h inst_pre.h
inst_easy.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_easy.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_easy.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_easy.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_easy.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_easy.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_easy.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_easy.o: /usr/include/alloca.h /usr/include/stdio.h
inst_easy.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_easy.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_easy.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_easy.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_easy.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_easy.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_easy.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_easy.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_easy.o: /usr/include/machine/types.h /usr/include/endian.h
inst_easy.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_easy.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_easy.o: /usr/include/sys/times.h output.h memory.h /usr/include/string.h
inst_easy.o: /usr/include/sys/string.h expressions.h inst_pre.h inst_easy.h
inst_hard.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_hard.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_hard.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_hard.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_hard.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_hard.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_hard.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_hard.o: /usr/include/alloca.h /usr/include/stdio.h
inst_hard.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_hard.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_hard.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_hard.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_hard.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_hard.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_hard.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_hard.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_hard.o: /usr/include/machine/types.h /usr/include/endian.h
inst_hard.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_hard.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_hard.o: /usr/include/sys/times.h output.h memory.h /usr/include/string.h
inst_hard.o: /usr/include/sys/string.h expressions.h inst_pre.h inst_hard.h
inst_final.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
inst_final.o: /usr/include/_ansi.h /usr/include/newlib.h
inst_final.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
inst_final.o: /usr/include/sys/features.h /usr/include/sys/reent.h
inst_final.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
inst_final.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
inst_final.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
inst_final.o: /usr/include/alloca.h /usr/include/stdio.h
inst_final.o: /usr/include/sys/stdio.h /usr/include/strings.h
inst_final.o: /usr/include/sys/_locale.h /usr/include/ctype.h
inst_final.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
inst_final.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
inst_final.o: /usr/include/bits/endian.h /usr/include/sys/select.h
inst_final.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
inst_final.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
inst_final.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
inst_final.o: /usr/include/machine/types.h /usr/include/endian.h
inst_final.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
inst_final.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
inst_final.o: /usr/include/sys/times.h output.h memory.h
inst_final.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
inst_final.o: inst_pre.h inst_final.h
relax.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
relax.o: /usr/include/_ansi.h /usr/include/newlib.h
relax.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
relax.o: /usr/include/sys/features.h /usr/include/sys/reent.h
relax.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
relax.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
relax.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
relax.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
relax.o: /usr/include/strings.h /usr/include/sys/_locale.h
relax.o: /usr/include/ctype.h /usr/include/sys/types.h
relax.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
relax.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
relax.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
relax.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
relax.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
relax.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
relax.o: /usr/include/endian.h /usr/include/bits/byteswap.h
relax.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
relax.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h memory.h
relax.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
relax.o: relax.h search.h
search.o: ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
search.o: /usr/include/_ansi.h /usr/include/newlib.h
search.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
search.o: /usr/include/sys/features.h /usr/include/sys/reent.h
search.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
search.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
search.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
search.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/sys/stdio.h
search.o: /usr/include/strings.h /usr/include/sys/_locale.h
search.o: /usr/include/ctype.h /usr/include/sys/types.h
search.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
search.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
search.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
search.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
search.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
search.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
search.o: /usr/include/endian.h /usr/include/bits/byteswap.h
search.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
search.o: /usr/include/sys/timeb.h /usr/include/sys/times.h output.h memory.h
search.o: /usr/include/string.h /usr/include/sys/string.h expressions.h
search.o: relax.h search.h
utility.o: /usr/include/string.h /usr/include/_ansi.h /usr/include/newlib.h
utility.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
utility.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
utility.o: /usr/include/sys/reent.h /usr/include/sys/cdefs.h
utility.o: /usr/include/machine/_default_types.h /usr/include/sys/_types.h
utility.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
utility.o: /usr/include/sys/_locale.h /usr/include/strings.h
utility.o: /usr/include/sys/string.h utility.h ff.h /usr/include/stdlib.h
utility.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
utility.o: /usr/include/stdio.h /usr/include/sys/stdio.h /usr/include/ctype.h
utility.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
utility.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
utility.o: /usr/include/bits/endian.h /usr/include/sys/select.h
utility.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
utility.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
utility.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
utility.o: /usr/include/machine/types.h /usr/include/endian.h
utility.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
utility.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
utility.o: /usr/include/sys/times.h output.h
test_main.o: libff.h ff.h /usr/include/stdlib.h /usr/include/machine/ieeefp.h
test_main.o: /usr/include/_ansi.h /usr/include/newlib.h
test_main.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
test_main.o: /usr/include/sys/features.h /usr/include/sys/reent.h
test_main.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
test_main.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
test_main.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
test_main.o: /usr/include/alloca.h /usr/include/stdio.h
test_main.o: /usr/include/sys/stdio.h /usr/include/strings.h
test_main.o: /usr/include/sys/_locale.h /usr/include/ctype.h
test_main.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
test_main.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
test_main.o: /usr/include/bits/endian.h /usr/include/sys/select.h
test_main.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
test_main.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
test_main.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/cpuset.h
test_main.o: /usr/include/machine/types.h /usr/include/endian.h
test_main.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
test_main.o: /usr/include/sys/sysmacros.h /usr/include/sys/timeb.h
test_main.o: /usr/include/sys/times.h output.h
