CC = g++
BISON = bison
FLEX = flex

NFF_TARGET = pr2plan_complex

#CXXFLAGS = -g -Wall -Imod-metric-ff -DDEBUG -DPDDL_TYPE_CHECKING
CXXFLAGS = -O3 -Wall -Imod-metric-ff -DNDEBUG
LDFLAGS = -Lmod-metric-ff/
#EFENCE = -lefence
# STATIC = -static   #Only uncomment if you're willing to include all the C libraries down south.
LIBS = -lff $(EFENCE)

NFF_SOURCES = PDDL.cxx \
	pddl_fluent_set.cxx \
	pddl_string_table.cxx \
	bitarray.cxx \
	global_options.cxx \
	options.cxx \
	pr_obs_reader.cxx \
	pr_strips_mapping.cxx \
	strips_writer.cxx \
	act_obs.cxx \
	main.cxx \
	act_obs_complex.cxx \
	pr_strips_mapping_complex.cxx

NFF_OBJECTS = $(NFF_SOURCES:.cxx=.o)

# Implicit rules
#
.SUFFIXES:

.SUFFIXES: .cxx .C .o

.cxx.o:; $(CC) -o $@ -c $(CXXFLAGS) $<
.C.o:; $(CC) -o $@ -c $(CXXFLAGS) $<

# build rules

all : $(NFF_TARGET)

$(NFF_TARGET) : $(PARSER_OBJ) $(NFF_OBJECTS)
	$(CC) -o $(NFF_TARGET) $(STATIC) $(PARSER_OBJ) $(NFF_OBJECTS) $(LDFLAGS) $(LIBS)

# dependencies
depend:
	# Updating dependencies
	@makedepend -- $(CXXFLAGS) -- $(NFF_SOURCES) $(MAIN_NFF_SOURCES)

# Cleaning
clean:
	rm -rf $(NFF_OBJECTS) $(NFF_TARGET) $(PARSER_SRC)  $(PARSER_HDR) *.o *.hh
# DO NOT DELETE

PDDL.o: PDDL.hxx pddl_basic_types.hxx pddl_string_table.hxx
PDDL.o: pddl_fluent_set.hxx bitarray.hxx nff_logic.hxx /usr/include/stdint.h
PDDL.o: /usr/include/machine/_default_types.h /usr/include/sys/features.h
PDDL.o: /usr/include/_newlib_version.h /usr/include/sys/_intsup.h
PDDL.o: /usr/include/sys/_stdint.h utils.hxx /usr/include/sys/times.h
PDDL.o: /usr/include/_ansi.h /usr/include/newlib.h /usr/include/sys/config.h
PDDL.o: /usr/include/machine/ieeefp.h /usr/include/sys/_types.h
PDDL.o: /usr/include/machine/_types.h /usr/include/sys/resource.h
PDDL.o: /usr/include/sys/time.h /usr/include/sys/cdefs.h
PDDL.o: /usr/include/sys/_timeval.h /usr/include/sys/types.h
PDDL.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
PDDL.o: /usr/include/bits/endian.h /usr/include/sys/select.h
PDDL.o: /usr/include/sys/_sigset.h /usr/include/sys/timespec.h
PDDL.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
PDDL.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
PDDL.o: /usr/include/endian.h /usr/include/bits/byteswap.h
PDDL.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
PDDL.o: /usr/include/time.h /usr/include/sys/reent.h /usr/include/sys/lock.h
PDDL.o: /usr/include/machine/time.h /usr/include/sys/_locale.h
PDDL.o: /usr/include/machine/_time.h /usr/include/unistd.h
PDDL.o: /usr/include/sys/unistd.h options.hxx mod-metric-ff/libff.h
PDDL.o: mod-metric-ff/ff.h /usr/include/stdlib.h
PDDL.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
PDDL.o: /usr/include/stdio.h /usr/include/sys/stdio.h /usr/include/strings.h
PDDL.o: /usr/include/ctype.h /usr/include/sys/timeb.h
pddl_fluent_set.o: pddl_fluent_set.hxx bitarray.hxx
pddl_string_table.o: pddl_string_table.hxx pddl_basic_types.hxx
bitarray.o: bitarray.hxx
global_options.o: global_options.hxx
options.o: options.hxx /usr/include/getopt.h
pr_obs_reader.o: pr_obs_reader.hxx act_obs.hxx string_ops.hxx PDDL.hxx
pr_obs_reader.o: pddl_basic_types.hxx pddl_string_table.hxx
pr_obs_reader.o: pddl_fluent_set.hxx bitarray.hxx nff_logic.hxx
pr_obs_reader.o: /usr/include/stdint.h /usr/include/machine/_default_types.h
pr_obs_reader.o: /usr/include/sys/features.h /usr/include/_newlib_version.h
pr_obs_reader.o: /usr/include/sys/_intsup.h /usr/include/sys/_stdint.h
pr_strips_mapping.o: pr_strips_mapping.hxx strips_writer.hxx act_obs.hxx
pr_strips_mapping.o: PDDL.hxx pddl_basic_types.hxx pddl_string_table.hxx
pr_strips_mapping.o: pddl_fluent_set.hxx bitarray.hxx nff_logic.hxx
pr_strips_mapping.o: /usr/include/stdint.h
pr_strips_mapping.o: /usr/include/machine/_default_types.h
pr_strips_mapping.o: /usr/include/sys/features.h
pr_strips_mapping.o: /usr/include/_newlib_version.h
pr_strips_mapping.o: /usr/include/sys/_intsup.h /usr/include/sys/_stdint.h
pr_strips_mapping.o: options.hxx
strips_writer.o: strips_writer.hxx PDDL.hxx pddl_basic_types.hxx
strips_writer.o: pddl_string_table.hxx pddl_fluent_set.hxx bitarray.hxx
strips_writer.o: nff_logic.hxx /usr/include/stdint.h
strips_writer.o: /usr/include/machine/_default_types.h
strips_writer.o: /usr/include/sys/features.h /usr/include/_newlib_version.h
strips_writer.o: /usr/include/sys/_intsup.h /usr/include/sys/_stdint.h
strips_writer.o: string_ops.hxx
act_obs.o: act_obs.hxx pddl_string_table.hxx pddl_basic_types.hxx PDDL.hxx
act_obs.o: pddl_fluent_set.hxx bitarray.hxx nff_logic.hxx
act_obs.o: /usr/include/stdint.h /usr/include/machine/_default_types.h
act_obs.o: /usr/include/sys/features.h /usr/include/_newlib_version.h
act_obs.o: /usr/include/sys/_intsup.h /usr/include/sys/_stdint.h
main.o: /usr/include/signal.h /usr/include/_ansi.h /usr/include/newlib.h
main.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
main.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
main.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
main.o: /usr/include/sys/signal.h /usr/include/sys/types.h
main.o: /usr/include/machine/_types.h /usr/include/sys/_types.h
main.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
main.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
main.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
main.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
main.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
main.o: /usr/include/sys/cpuset.h /usr/include/machine/types.h
main.o: /usr/include/endian.h /usr/include/bits/byteswap.h
main.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
main.o: /usr/include/stdint.h /usr/include/sys/_intsup.h utils.hxx
main.o: /usr/include/sys/times.h /usr/include/sys/resource.h
main.o: /usr/include/sys/time.h /usr/include/time.h /usr/include/sys/reent.h
main.o: /usr/include/sys/lock.h /usr/include/machine/time.h
main.o: /usr/include/sys/_locale.h /usr/include/machine/_time.h
main.o: /usr/include/unistd.h /usr/include/sys/unistd.h PDDL.hxx
main.o: pddl_basic_types.hxx pddl_string_table.hxx pddl_fluent_set.hxx
main.o: bitarray.hxx nff_logic.hxx options.hxx pr_obs_reader.hxx act_obs.hxx
main.o: pr_strips_mapping.hxx strips_writer.hxx string_ops.hxx
main.o: act_obs_complex.hxx pr_strips_mapping_complex.hxx
act_obs_complex.o: act_obs_complex.hxx PDDL.hxx pddl_basic_types.hxx
act_obs_complex.o: pddl_string_table.hxx pddl_fluent_set.hxx bitarray.hxx
act_obs_complex.o: nff_logic.hxx /usr/include/stdint.h
act_obs_complex.o: /usr/include/machine/_default_types.h
act_obs_complex.o: /usr/include/sys/features.h /usr/include/_newlib_version.h
act_obs_complex.o: /usr/include/sys/_intsup.h /usr/include/sys/_stdint.h
act_obs_complex.o: string_ops.hxx
pr_strips_mapping_complex.o: pr_strips_mapping_complex.hxx strips_writer.hxx
pr_strips_mapping_complex.o: act_obs_complex.hxx PDDL.hxx
pr_strips_mapping_complex.o: pddl_basic_types.hxx pddl_string_table.hxx
pr_strips_mapping_complex.o: pddl_fluent_set.hxx bitarray.hxx nff_logic.hxx
pr_strips_mapping_complex.o: /usr/include/stdint.h
pr_strips_mapping_complex.o: /usr/include/machine/_default_types.h
pr_strips_mapping_complex.o: /usr/include/sys/features.h
pr_strips_mapping_complex.o: /usr/include/_newlib_version.h
pr_strips_mapping_complex.o: /usr/include/sys/_intsup.h
pr_strips_mapping_complex.o: /usr/include/sys/_stdint.h options.hxx
